export const mockChiaYiFile = {
  '1Line': [{
    'id': 0,
    'stopName': '嘉義',
    'stopType': '-1'
  }, {
    'id': 1,
    'stopName': '第一銀行',
    'stopType': '-1'
  }, {
    'id': 2,
    'stopName': '公明路',
    'stopType': '-1'
  }, {
    'id': 3,
    'stopName': '市政府',
    'stopType': '-1'
  }, {
    'id': 4,
    'stopName': '文化中心',
    'stopType': '-1'
  }, {
    'id': 5,
    'stopName': '台斗街',
    'stopType': '0'
  }, {
    'id': 6,
    'stopName': '後湖',
    'stopType': '1'
  }, {
    'id': 7,
    'stopName': '宏仁女中',
    'stopType': '1'
  }],
  '2Lines': [
    {
    'id': 0,
    'stopName': '嘉義',
    'stopType': '-1'
    }, {
      'id': 1,
      'stopName': '第一銀行',
      'stopType': '-1'
    }, {
      'id': 2,
      'stopName': '公明路',
      'stopType': '-1'
    }, {
      'id': 3,
      'stopName': '市政府',
      'stopType': '-1'
    }, {
      'id': 4,
      'stopName': '文化中心',
      'stopType': '-1'
    }, {
      'id': 5,
      'stopName': '台斗街',
      'stopType': '-1'
    }, {
      'id': 6,
      'stopName': '後湖',
      'stopType': '-1'
    }, {
      'id': 7,
      'stopName': '宏仁女中',
      'stopType': '-1'
    }, {
      'id': 8,
      'stopName': '荖籐宅',
      'stopType': '-1'
    }, {
      'id': 9,
      'stopName': '忠孝北街',
      'stopType': '-1'
    }, {
      'id': 10,
      'stopName': '頭橋工業區',
      'stopType': '-1'
    }, {
      'id': 11,
      'stopName': '頭橋',
      'stopType': '-1'
    }, {
      'id': 12,
      'stopName': '福樂新村',
      'stopType': '-1'
    }, {
      'id': 13,
      'stopName': '協同中學',
      'stopType': '0'
    }, {
      'id': 14,
      'stopName': '吳鳳科技大學',
      'stopType': '1'
    }, {
      'id': 15,
      'stopName': '雙福',
      'stopType': '1'
    }, {
      'id': 16,
      'stopName': '民雄稅捐處',
      'stopType': '1'
    }, {
      'id': 17,
      'stopName': '協志高中',
      'stopType': '1'
    }, {
      'id': 18,
      'stopName': '民雄鄉公所',
      'stopType': '1'
    }, {
      'id': 19,
      'stopName': '民雄',
      'stopType': '1'
    }, {
      'id': 20,
      'stopName': '溪口路口',
      'stopType': '1'
    }, {
      'id': 21,
      'stopName': '民雄國中',
      'stopType': '1'
    }, {
      'id': 22,
      'stopName': '福權村1',
      'stopType': '1'
    }, {
      'id': 23,
      'stopName': '福權村2',
      'stopType': '1'
    }, {
      'id': 24,
      'stopName': '菁埔',
      'stopType': '1'
    }, {
      'id': 25,
      'stopName': '西庄',
      'stopType': '1'
    }, {
      'id': 26,
      'stopName': '大潭',
      'stopType': '1'
    }, {
      'id': 27,
      'stopName': '三王公廟',
      'stopType': '1'
    }, {
      'id': 28,
      'stopName': '宮前',
      'stopType': '1'
    }, {
      'id': 29,
      'stopName': '東頭',
      'stopType': '1'
    }, {
      'id': 30,
      'stopName': '新港',
      'stopType': '1'
    }, {
      'id': 31,
      'stopName': '新港國中',
      'stopType': '1'
    }, {
      'id': 32,
      'stopName': '後庄路口',
      'stopType': '1'
    }, {
      'id': 33,
      'stopName': '老塗獅',
      'stopType': '1'
    }, {
      'id': 34,
      'stopName': '南壇',
      'stopType': '1'
    }, {
      'id': 35,
      'stopName': '南港派出所',
      'stopType': '1'
    }, {
      'id': 36,
      'stopName': '板頭路口',
      'stopType': '1'
    }, {
      'id': 37,
      'stopName': '水仙宮',
      'stopType': '1'
    }],
  '3Lines': [
    {
    'id': 0,
    'stopName': '嘉義',
    'stopType': '-1'
    }, {
      'id': 1,
      'stopName': '第一銀行',
      'stopType': '-1'
    }, {
      'id': 2,
      'stopName': '公明路',
      'stopType': '-1'
    }, {
      'id': 3,
      'stopName': '市政府',
      'stopType': '-1'
    }, {
      'id': 4,
      'stopName': '文化中心',
      'stopType': '-1'
    }, {
      'id': 5,
      'stopName': '台斗街',
      'stopType': '-1'
    }, {
      'id': 6,
      'stopName': '後湖',
      'stopType': '-1'
    }, {
      'id': 7,
      'stopName': '宏仁女中',
      'stopType': '-1'
    }, {
      'id': 8,
      'stopName': '荖籐宅',
      'stopType': '-1'
    }, {
      'id': 9,
      'stopName': '忠孝北街',
      'stopType': '-1'
    }, {
      'id': 10,
      'stopName': '頭橋工業區',
      'stopType': '-1'
    }, {
      'id': 11,
      'stopName': '頭橋',
      'stopType': '-1'
    }, {
      'id': 12,
      'stopName': '福樂新村',
      'stopType': '-1'
    }, {
      'id': 13,
      'stopName': '協同中學',
      'stopType': '0'
    }, {
      'id': 14,
      'stopName': '吳鳳科技大學',
      'stopType': '1'
    }, {
      'id': 15,
      'stopName': '雙福',
      'stopType': '1'
    }, {
      'id': 16,
      'stopName': '民雄稅捐處',
      'stopType': '1'
    }, {
      'id': 17,
      'stopName': '協志高中',
      'stopType': '1'
    }, {
      'id': 18,
      'stopName': '民雄鄉公所',
      'stopType': '1'
    }, {
      'id': 19,
      'stopName': '民雄',
      'stopType': '1'
    }, {
      'id': 20,
      'stopName': '溪口路口',
      'stopType': '1'
    }, {
      'id': 21,
      'stopName': '民雄國中',
      'stopType': '1'
    }, {
      'id': 22,
      'stopName': '福權村1',
      'stopType': '1'
    }, {
      'id': 23,
      'stopName': '福權村2',
      'stopType': '1'
    }, {
      'id': 24,
      'stopName': '菁埔',
      'stopType': '1'
    }, {
      'id': 25,
      'stopName': '西庄',
      'stopType': '1'
    }, {
      'id': 26,
      'stopName': '大潭',
      'stopType': '1'
    }, {
      'id': 27,
      'stopName': '三王公廟',
      'stopType': '1'
    }, {
      'id': 28,
      'stopName': '宮前',
      'stopType': '1'
    }, {
      'id': 29,
      'stopName': '東頭',
      'stopType': '1'
    }, {
      'id': 30,
      'stopName': '新港',
      'stopType': '1'
    }, {
      'id': 31,
      'stopName': '新港國中',
      'stopType': '1'
    }, {
      'id': 32,
      'stopName': '後庄路口',
      'stopType': '1'
    }, {
      'id': 33,
      'stopName': '老塗獅',
      'stopType': '1'
    }, {
      'id': 34,
      'stopName': '南壇',
      'stopType': '1'
    }, {
      'id': 35,
      'stopName': '南港派出所',
      'stopType': '1'
    }, {
      'id': 36,
      'stopName': '板頭路口',
      'stopType': '1'
    }, {
      'id': 37,
      'stopName': '水仙宮',
      'stopType': '1'
    }, {
      'id': 38,
      'stopName': '安和路口',
      'stopType': '1'
    }, {
      'id': 39,
      'stopName': '崙陽路口',
      'stopType': '1'
    }, {
      'id': 40,
      'stopName': '蘇厝寮',
      'stopType': '1'
    }, {
      'id': 41,
      'stopName': '北港派出所',
      'stopType': '1'
    }, {
      'id': 42,
      'stopName': '北港',
      'stopType': '1'
    }],
  '4Lines': [
    {
      'id': 0,
      'stopName': '大雅站',
      'stopType': '-1'
    }, {
      'id': 1,
      'stopName': '二二八紀念館',
      'stopType': '-1'
    }, {
      'id': 2,
      'stopName': '民族停車場',
      'stopType': '-1'
    }, {
      'id': 3,
      'stopName': '文化路口',
      'stopType': '-1'
    }, {
      'id': 4,
      'stopName': '新光三越遠東站',
      'stopType': '-1'
    }, {
      'id': 5,
      'stopName': '嘉義火車站',
      'stopType': '-1'
    }, {
      'id': 6,
      'stopName': '彰化銀行',
      'stopType': '-1'
    }, {
      'id': 7,
      'stopName': '中央噴水站',
      'stopType': '-1'
    }, {
      'id': 8,
      'stopName': '市府站',
      'stopType': '-1'
    }, {
      'id': 9,
      'stopName': '文化中心',
      'stopType': '-1'
    }, {
      'id': 10,
      'stopName': '台斗坑',
      'stopType': '-1'
    }, {
      'id': 11,
      'stopName': '後湖',
      'stopType': '-1'
    }, {
      'id': 12,
      'stopName': '宏仁女中',
      'stopType': '-1'
    }, {
      'id': 13,
      'stopName': '遠東機械廠',
      'stopType': '-1'
    }, {
      'id': 14,
      'stopName': '忠孝北街口',
      'stopType': '-1'
    }, {
      'id': 15,
      'stopName': '頭橋工業區',
      'stopType': '-1'
    }, {
      'id': 16,
      'stopName': '頭橋',
      'stopType': '-1'
    }, {
      'id': 17,
      'stopName': '福樂新村',
      'stopType': '-1'
    }, {
      'id': 18,
      'stopName': '協同中學',
      'stopType': '0'
    }, {
      'id': 19,
      'stopName': '吳鳳科技大學',
      'stopType': '1'
    }, {
      'id': 20,
      'stopName': '雙福村',
      'stopType': '1'
    }, {
      'id': 21,
      'stopName': '民雄稅捐處',
      'stopType': '1'
    }, {
      'id': 22,
      'stopName': '協志高職',
      'stopType': '1'
    }, {
      'id': 23,
      'stopName': '民雄',
      'stopType': '1'
    }, {
      'id': 24,
      'stopName': '崙子頂',
      'stopType': '1'
    }, {
      'id': 25,
      'stopName': '鎮北村',
      'stopType': '1'
    }, {
      'id': 26,
      'stopName': '三疊溪',
      'stopType': '1'
    }, {
      'id': 27,
      'stopName': '昭慶寺',
      'stopType': '1'
    }, {
      'id': 28,
      'stopName': '加油站',
      'stopType': '1'
    }, {
      'id': 29,
      'stopName': '大林',
      'stopType': '1'
    }, {
      'id': 30,
      'stopName': '大林國中',
      'stopType': '1'
    }, {
      'id': 31,
      'stopName': '果菜市場',
      'stopType': '1'
    }, {
      'id': 32,
      'stopName': '水源路',
      'stopType': '1'
    }, {
      'id': 33,
      'stopName': '東大林',
      'stopType': '1'
    }, {
      'id': 34,
      'stopName': '老人養護中心',
      'stopType': '1'
    }, {
      'id': 35,
      'stopName': '大林鎮公所',
      'stopType': '1'
    }, {
      'id': 36,
      'stopName': '水碓',
      'stopType': '1'
    }, {
      'id': 37,
      'stopName': '林子前路口',
      'stopType': '1'
    }, {
      'id': 38,
      'stopName': '麗園社區',
      'stopType': '1'
    }, {
      'id': 39,
      'stopName': '林子前',
      'stopType': '1'
    }, {
      'id': 40,
      'stopName': '變電所',
      'stopType': '1'
    }, {
      'id': 41,
      'stopName': '過溪',
      'stopType': '1'
    }, {
      'id': 42,
      'stopName': '大埔美',
      'stopType': '1'
    }, {
      'id': 43,
      'stopName': '油車店',
      'stopType': '1'
    }, {
      'id': 44,
      'stopName': '集貨場',
      'stopType': '1'
    }, {
      'id': 45,
      'stopName': '互助社區',
      'stopType': '1'
    }, {
      'id': 46,
      'stopName': '崎頭',
      'stopType': '1'
    }, {
      'id': 47,
      'stopName': '崎頂營房',
      'stopType': '1'
    }, {
      'id': 48,
      'stopName': '新崎頂',
      'stopType': '1'
    }, {
      'id': 49,
      'stopName': '崎頂',
      'stopType': '1'
    }, {
      'id': 50,
      'stopName': '過山村',
      'stopType': '1'
    }, {
      'id': 51,
      'stopName': '梅山工業區',
      'stopType': '1'
    }, {
      'id': 52,
      'stopName': '尾庄',
      'stopType': '1'
    }, {
      'id': 53,
      'stopName': '新社區',
      'stopType': '1'
    }, {
      'id': 54,
      'stopName': '電信局',
      'stopType': '1'
    }, {
      'id': 55,
      'stopName': '梅山鄉公所',
      'stopType': '1'
    }, {
      'id': 56,
      'stopName': '梅北',
      'stopType': '1'
    }, {
      'id': 57,
      'stopName': '梅山市場',
      'stopType': '1'
    }, {
      'id': 58,
      'stopName': '玉虛宮',
      'stopType': '1'
    }, {
      'id': 59,
      'stopName': '梅山',
      'stopType': '1'
    }, {
      'id': 60,
      'stopName': '太平路口',
      'stopType': '1'
    }, {
      'id': 61,
      'stopName': '永興村',
      'stopType': '1'
    }, {
      'id': 62,
      'stopName': '頭前溪',
      'stopType': '1'
    }, {
      'id': 63,
      'stopName': '下半天',
      'stopType': '1'
    }, {
      'id': 64,
      'stopName': '下庄',
      'stopType': '1'
    }, {
      'id': 65,
      'stopName': '二坪子',
      'stopType': '1'
    }, {
      'id': 66,
      'stopName': '社區中心',
      'stopType': '1'
    }, {
      'id': 67,
      'stopName': '頂半天',
      'stopType': '1'
    }, {
      'id': 68,
      'stopName': '半天村',
      'stopType': '1'
    }, {
      'id': 69,
      'stopName': '半路店',
      'stopType': '1'
    }, {
      'id': 70,
      'stopName': '群彎',
      'stopType': '1'
    }, {
      'id': 71,
      'stopName': '平路',
      'stopType': '1'
    }, {
      'id': 72,
      'stopName': '雲海飯店',
      'stopType': '1'
    }, {
      'id': 73,
      'stopName': '望風台',
      'stopType': '1'
    }, {
      'id': 74,
      'stopName': '下坑仔',
      'stopType': '1'
    }, {
      'id': 75,
      'stopName': '太平',
      'stopType': '1'
    }, {
      'id': 76,
      'stopName': '東太平',
      'stopType': '1'
    }, {
      'id': 77,
      'stopName': '碧湖路口',
      'stopType': '1'
    }, {
      'id': 78,
      'stopName': '仙人堀',
      'stopType': '1'
    }, {
      'id': 79,
      'stopName': '碧湖崗哨',
      'stopType': '1'
    }, {
      'id': 80,
      'stopName': '堀尺嶺',
      'stopType': '1'
    }, {
      'id': 81,
      'stopName': '碧湖崗哨',
      'stopType': '1'
    }, {
      'id': 82,
      'stopName': '仙人堀',
      'stopType': '1'
    }, {
      'id': 83,
      'stopName': '大籠頂',
      'stopType': '1'
    }, {
      'id': 84,
      'stopName': '北茅仔埔',
      'stopType': '1'
    }, {
      'id': 85,
      'stopName': '茅仔埔',
      'stopType': '1'
    }, {
      'id': 86,
      'stopName': '橫山',
      'stopType': '1'
    }, {
      'id': 87,
      'stopName': '東橫山',
      'stopType': '1'
    }, {
      'id': 88,
      'stopName': '下寮',
      'stopType': '1'
    }, {
      'id': 89,
      'stopName': '後嶺',
      'stopType': '1'
    }, {
      'id': 90,
      'stopName': '太興國小',
      'stopType': '1'
    }, {
      'id': 91,
      'stopName': '科仔腳',
      'stopType': '1'
    }, {
      'id': 92,
      'stopName': '青園',
      'stopType': '1'
    }, {
      'id': 93,
      'stopName': '枝村',
      'stopType': '1'
    }, {
      'id': 94,
      'stopName': '石鼓坪',
      'stopType': '1'
    }, {
      'id': 95,
      'stopName': '交力坪',
      'stopType': '1'
    }, {
      'id': 96,
      'stopName': '雲潭瀑布',
      'stopType': '1'
    }, {
      'id': 97,
      'stopName': '瑞里山莊',
      'stopType': '1'
    }, {
      'id': 98,
      'stopName': '科仔林',
      'stopType': '1'
    }, {
      'id': 99,
      'stopName': '六號蕉',
      'stopType': '1'
    }, {
      'id': 100,
      'stopName': '竹仔籠',
      'stopType': '1'
    }, {
      'id': 101,
      'stopName': '若蘭山莊',
      'stopType': '1'
    }, {
      'id': 102,
      'stopName': '水車寮路口',
      'stopType': '1'
    }, {
      'id': 103,
      'stopName': '瑞里二坪',
      'stopType': '1'
    }, {
      'id': 104,
      'stopName': '梅花山莊',
      'stopType': '1'
    }, {
      'id': 105,
      'stopName': '瑞里國小',
      'stopType': '1'
    }, {
      'id': 106,
      'stopName': '柑園',
      'stopType': '1'
    }, {
      'id': 107,
      'stopName': '源興宮',
      'stopType': '1'
    }, {
      'id': 108,
      'stopName': '青葉山莊',
      'stopType': '1'
    }, {
      'id': 109,
      'stopName': '瑞里',
      'stopType': '1'
    }, {
      'id': 110,
      'stopName': '?埔坑',
      'stopType': '1'
    }, {
      'id': 111,
      'stopName': '農會瑞里分部',
      'stopType': '1'
    }, {
      'id': 112,
      'stopName': '?埔',
      'stopType': '1'
    }, {
      'id': 113,
      'stopName': '南天巨屏站',
      'stopType': '1'
    }, {
      'id': 114,
      'stopName': '新興寮',
      'stopType': '1'
    }, {
      'id': 115,
      'stopName': '瑞峰國小',
      'stopType': '1'
    }, {
      'id': 116,
      'stopName': '瑞峰',
      'stopType': '1'
    }],
}

export const mockYunlinFile = {
  '1Line': [
    {
    'id': 0,
    'stopName': '北港',
    'stopNameEng': 'Beigang',
    'stopType': '-1'
  }, {
    'id': 1,
    'stopName': '北港電力公司',
    'stopNameEng': 'Beigang Power Company',
    'stopType': '-1'
  }, {
    'id': 2,
    'stopName': '五路財神廟',
    'stopNameEng': 'Wulu Caishen Temple',
    'stopType': '-1'
  }, {
    'id': 3,
    'stopName': '新街',
    'stopNameEng': 'Xinjie',
    'stopType': '-1'
  }, {
    'id': 4,
    'stopName': '草湖',
    'stopNameEng': 'Caohu',
    'stopType': '-1'
  }, {
    'id': 5,
    'stopName': '頂草湖',
    'stopNameEng': 'Dingcaohu',
    'stopType': '-1'
  }, {
    'id': 6,
    'stopName': '溝皂',
    'stopNameEng': 'Gouzao',
    'stopType': '0'
  }, {
    'id': 7,
    'stopName': '西庄',
    'stopNameEng': 'Xizhuang',
    'stopType': '1'
  }, {
    'id': 8,
    'stopName': '頂西庄',
    'stopNameEng': 'Dingxizhuang',
    'stopType': '1'
  }],
  '2Lines': [
    {
      'id': 0,
      'stopName': '北港',
      'stopNameEng': 'Beigang',
      'stopType': '-1'
    }, {
      'id': 1,
      'stopName': '北港電力公司',
      'stopNameEng': 'Beigang Power Company',
      'stopType': '-1'
    }, {
      'id': 2,
      'stopName': '五路財神廟',
      'stopNameEng': 'Wulu Caishen Temple',
      'stopType': '-1'
    }, {
      'id': 3,
      'stopName': '新街',
      'stopNameEng': 'Xinjie',
      'stopType': '-1'
    }, {
      'id': 4,
      'stopName': '草湖',
      'stopNameEng': 'Caohu',
      'stopType': '-1'
    }, {
      'id': 5,
      'stopName': '頂草湖',
      'stopNameEng': 'Dingcaohu',
      'stopType': '-1'
    }, {
      'id': 6,
      'stopName': '溝皂',
      'stopNameEng': 'Gouzao',
      'stopType': '-1'
    }, {
      'id': 7,
      'stopName': '西庄',
      'stopNameEng': 'Xizhuang',
      'stopType': '-1'
    }, {
      'id': 8,
      'stopName': '頂西庄',
      'stopNameEng': 'Dingxizhuang',
      'stopType': '-1'
    }, {
      'id': 9,
      'stopName': '白花墓',
      'stopNameEng': 'Bai hua mu',
      'stopType': '-1'
    }, {
      'id': 10,
      'stopName': '元長1',
      'stopNameEng': 'Yuanzhang1',
      'stopType': '-1'
    }, {
      'id': 11,
      'stopName': '元長',
      'stopNameEng': 'Yuanchang',
      'stopType': '-1'
    }, {
      'id': 12,
      'stopName': '子茂',
      'stopNameEng': 'Zimau',
      'stopType': '-1'
    }, {
      'id': 13,
      'stopName': '和平國小',
      'stopNameEng': 'Heping ES.',
      'stopType': '-1'
    }, {
      'id': 14,
      'stopName': '秀潭',
      'stopNameEng': 'Xiutan',
      'stopType': '-1'
    }, {
      'id': 15,
      'stopName': '奮起湖',
      'stopNameEng': 'Fenqihu',
      'stopType': '-1'
    }, {
      'id': 16,
      'stopName': '義雲宮',
      'stopNameEng': 'Yiyun Temple',
      'stopType': '-1'
    }, {
      'id': 17,
      'stopName': '新興',
      'stopNameEng': 'Xinxing',
      'stopType': '-1'
    }, {
      'id': 18,
      'stopName': '下店',
      'stopNameEng': 'Xiadian',
      'stopType': '-1'
    }, {
      'id': 19,
      'stopName': '土庫商工',
      'stopNameEng': 'Tuku Vocational High',
      'stopType': '-1'
    }, {
      'id': 20,
      'stopName': '土庫',
      'stopNameEng': 'Tuku',
      'stopType': '-1'
    }, {
      'id': 21,
      'stopName': '永年中學',
      'stopNameEng': 'Yongnian High School',
      'stopType': '-1'
    }, {
      'id': 22,
      'stopName': '下湳',
      'stopNameEng': 'Xianan',
      'stopType': '-1'
    }, {
      'id': 23,
      'stopName': '中湳',
      'stopNameEng': 'Zhongnan',
      'stopType': '-1'
    }, {
      'id': 24,
      'stopName': '頂湳',
      'stopNameEng': 'Dingnan',
      'stopType': '-1'
    }, {
      'id': 25,
      'stopName': '虎尾科技大學',
      'stopNameEng': 'NFU',
      'stopType': '-1'
    }, {
      'id': 26,
      'stopName': '虎尾',
      'stopNameEng': 'Huwei',
      'stopType': '-1'
    }, {
      'id': 27,
      'stopName': '勝源',
      'stopNameEng': 'Shengyuan',
      'stopType': '-1'
    }, {
      'id': 28,
      'stopName': '埒內社區',
      'stopNameEng': 'Lenei Community',
      'stopType': '-1'
    }, {
      'id': 29,
      'stopName': '埒內',
      'stopNameEng': 'Lenei',
      'stopType': '-1'
    }, {
      'id': 30,
      'stopName': '汕尾',
      'stopNameEng': 'Shanwei',
      'stopType': '-1'
    }, {
      'id': 31,
      'stopName': '虎尾國中',
      'stopNameEng': 'Huwei Junior High',
      'stopType': '0'
    }, {
      'id': 32,
      'stopName': '半路店',
      'stopNameEng': 'Banludian',
      'stopType': '1'
    }, {
      'id': 33,
      'stopName': '中溪',
      'stopNameEng': 'Zhongxi',
      'stopType': '1'
    }, {
      'id': 34,
      'stopName': '東過溪',
      'stopNameEng': 'Dongguoxi',
      'stopType': '1'
    }, {
      'id': 35,
      'stopName': '崁腳',
      'stopNameEng': 'Kanjiao',
      'stopType': '1'
    }, {
      'id': 36,
      'stopName': '大路墘',
      'stopNameEng': 'Daluqian',
      'stopType': '1'
    }
  ],
  '3Lines': [
    {
      'id': 0,
      'stopName': '北港',
      'stopNameEng': 'Beigang',
      'stopType': '-1'
    }, {
      'id': 1,
      'stopName': '北港電力公司',
      'stopNameEng': 'Beigang Power Company',
      'stopType': '-1'
    }, {
      'id': 2,
      'stopName': '五路財神廟',
      'stopNameEng': 'Wulu Caishen Temple',
      'stopType': '-1'
    }, {
      'id': 3,
      'stopName': '新街',
      'stopNameEng': 'Xinjie',
      'stopType': '-1'
    }, {
      'id': 4,
      'stopName': '草湖',
      'stopNameEng': 'Caohu',
      'stopType': '-1'
    }, {
      'id': 5,
      'stopName': '頂草湖',
      'stopNameEng': 'Dingcaohu',
      'stopType': '-1'
    }, {
      'id': 6,
      'stopName': '溝皂',
      'stopNameEng': 'Gouzao',
      'stopType': '-1'
    }, {
      'id': 7,
      'stopName': '西庄',
      'stopNameEng': 'Xizhuang',
      'stopType': '-1'
    }, {
      'id': 8,
      'stopName': '頂西庄',
      'stopNameEng': 'Dingxizhuang',
      'stopType': '-1'
    }, {
      'id': 9,
      'stopName': '白花墓',
      'stopNameEng': 'Bai hua mu',
      'stopType': '-1'
    }, {
      'id': 10,
      'stopName': '元長1',
      'stopNameEng': 'Yuanzhang1',
      'stopType': '-1'
    }, {
      'id': 11,
      'stopName': '元長',
      'stopNameEng': 'Yuanchang',
      'stopType': '-1'
    }, {
      'id': 12,
      'stopName': '子茂',
      'stopNameEng': 'Zimau',
      'stopType': '-1'
    }, {
      'id': 13,
      'stopName': '和平國小',
      'stopNameEng': 'Heping ES.',
      'stopType': '-1'
    }, {
      'id': 14,
      'stopName': '秀潭',
      'stopNameEng': 'Xiutan',
      'stopType': '-1'
    }, {
      'id': 15,
      'stopName': '奮起湖',
      'stopNameEng': 'Fenqihu',
      'stopType': '-1'
    }, {
      'id': 16,
      'stopName': '義雲宮',
      'stopNameEng': 'Yiyun Temple',
      'stopType': '-1'
    }, {
      'id': 17,
      'stopName': '新興',
      'stopNameEng': 'Xinxing',
      'stopType': '-1'
    }, {
      'id': 18,
      'stopName': '下店',
      'stopNameEng': 'Xiadian',
      'stopType': '-1'
    }, {
      'id': 19,
      'stopName': '土庫商工',
      'stopNameEng': 'Tuku Vocational High',
      'stopType': '-1'
    }, {
      'id': 20,
      'stopName': '土庫',
      'stopNameEng': 'Tuku',
      'stopType': '-1'
    }, {
      'id': 21,
      'stopName': '永年中學',
      'stopNameEng': 'Yongnian High School',
      'stopType': '-1'
    }, {
      'id': 22,
      'stopName': '下湳',
      'stopNameEng': 'Xianan',
      'stopType': '-1'
    }, {
      'id': 23,
      'stopName': '中湳',
      'stopNameEng': 'Zhongnan',
      'stopType': '-1'
    }, {
      'id': 24,
      'stopName': '頂湳',
      'stopNameEng': 'Dingnan',
      'stopType': '-1'
    }, {
      'id': 25,
      'stopName': '虎尾科技大學',
      'stopNameEng': 'NFU',
      'stopType': '-1'
    }, {
      'id': 26,
      'stopName': '虎尾',
      'stopNameEng': 'Huwei',
      'stopType': '-1'
    }, {
      'id': 27,
      'stopName': '勝源',
      'stopNameEng': 'Shengyuan',
      'stopType': '-1'
    }, {
      'id': 28,
      'stopName': '埒內社區',
      'stopNameEng': 'Lenei Community',
      'stopType': '-1'
    }, {
      'id': 29,
      'stopName': '埒內',
      'stopNameEng': 'Lenei',
      'stopType': '-1'
    }, {
      'id': 30,
      'stopName': '汕尾',
      'stopNameEng': 'Shanwei',
      'stopType': '-1'
    }, {
      'id': 31,
      'stopName': '虎尾國中',
      'stopNameEng': 'Huwei Junior High',
      'stopType': '0'
    }, {
      'id': 32,
      'stopName': '半路店',
      'stopNameEng': 'Banludian',
      'stopType': '1'
    }, {
      'id': 33,
      'stopName': '中溪',
      'stopNameEng': 'Zhongxi',
      'stopType': '1'
    }, {
      'id': 34,
      'stopName': '東過溪',
      'stopNameEng': 'Dongguoxi',
      'stopType': '1'
    }, {
      'id': 35,
      'stopName': '崁腳',
      'stopNameEng': 'Kanjiao',
      'stopType': '1'
    }, {
      'id': 36,
      'stopName': '大路墘',
      'stopNameEng': 'Daluqian',
      'stopType': '1'
    }, {
      'id': 37,
      'stopName': '惠來國小',
      'stopNameEng': 'Huilai ES.',
      'stopType': '1'
    }, {
      'id': 38,
      'stopName': '惠來厝',
      'stopNameEng': 'Huilaicuo',
      'stopType': '1'
    }, {
      'id': 39,
      'stopName': '溪底仔',
      'stopNameEng': 'Xi Di Zi',
      'stopType': '1'
    }, {
      'id': 40,
      'stopName': '大美瓦斯廠',
      'stopNameEng': 'Damei Gas Factory',
      'stopType': '1'
    }, {
      'id': 41,
      'stopName': '大美',
      'stopNameEng': 'Damei',
      'stopType': '1'
    }, {
      'id': 42,
      'stopName': '榮橋新村',
      'stopNameEng': 'Rongqiao Village',
      'stopType': '1'
    }, {
      'id': 43,
      'stopName': '豐泰',
      'stopNameEng': 'Fengtai',
      'stopType': '1'
    }, {
      'id': 44,
      'stopName': '虎尾溪',
      'stopNameEng': 'Huweixi',
      'stopType': '1'
    }, {
      'id': 45,
      'stopName': '正心中學',
      'stopNameEng': 'Zhengxin High school',
      'stopType': '1'
    }, {
      'id': 46,
      'stopName': '電力公司',
      'stopNameEng': 'Taiwan Power Company',
      'stopType': '1'
    }, {
      'id': 47,
      'stopName': '斗六',
      'stopNameEng': 'Douliu',
      'stopType': '1'
    }
  ],
  '4Lines': [
    {
      'id': 0,
      'stopName': '北港',
      'stopNameEng': 'Beigang',
      'stopType': '-1'
    }, {
      'id': 1,
      'stopName': '北港電力公司',
      'stopNameEng': 'Beigang Power Company',
      'stopType': '-1'
    }, {
      'id': 2,
      'stopName': '五路財神廟',
      'stopNameEng': 'Wulu Caishen Temple',
      'stopType': '-1'
    }, {
      'id': 3,
      'stopName': '新街',
      'stopNameEng': 'Xinjie',
      'stopType': '-1'
    }, {
      'id': 4,
      'stopName': '草湖',
      'stopNameEng': 'Caohu',
      'stopType': '-1'
    }, {
      'id': 5,
      'stopName': '頂草湖',
      'stopNameEng': 'Dingcaohu',
      'stopType': '-1'
    }, {
      'id': 6,
      'stopName': '溝皂',
      'stopNameEng': 'Gouzao',
      'stopType': '-1'
    }, {
      'id': 7,
      'stopName': '西庄',
      'stopNameEng': 'Xizhuang',
      'stopType': '-1'
    }, {
      'id': 8,
      'stopName': '頂西庄',
      'stopNameEng': 'Dingxizhuang',
      'stopType': '-1'
    }, {
      'id': 9,
      'stopName': '白花墓',
      'stopNameEng': 'Bai hua mu',
      'stopType': '-1'
    }, {
      'id': 10,
      'stopName': '元長1',
      'stopNameEng': 'Yuanzhang1',
      'stopType': '-1'
    }, {
      'id': 11,
      'stopName': '元長',
      'stopNameEng': 'Yuanchang',
      'stopType': '-1'
    }, {
      'id': 12,
      'stopName': '子茂',
      'stopNameEng': 'Zimau',
      'stopType': '-1'
    }, {
      'id': 13,
      'stopName': '和平國小',
      'stopNameEng': 'Heping ES.',
      'stopType': '-1'
    }, {
      'id': 14,
      'stopName': '秀潭',
      'stopNameEng': 'Xiutan',
      'stopType': '-1'
    }, {
      'id': 15,
      'stopName': '奮起湖',
      'stopNameEng': 'Fenqihu',
      'stopType': '-1'
    }, {
      'id': 16,
      'stopName': '義雲宮',
      'stopNameEng': 'Yiyun Temple',
      'stopType': '-1'
    }, {
      'id': 17,
      'stopName': '新興',
      'stopNameEng': 'Xinxing',
      'stopType': '-1'
    }, {
      'id': 18,
      'stopName': '下店',
      'stopNameEng': 'Xiadian',
      'stopType': '-1'
    }, {
      'id': 19,
      'stopName': '土庫商工',
      'stopNameEng': 'Tuku Vocational High',
      'stopType': '-1'
    }, {
      'id': 20,
      'stopName': '土庫',
      'stopNameEng': 'Tuku',
      'stopType': '-1'
    }, {
      'id': 21,
      'stopName': '永年中學',
      'stopNameEng': 'Yongnian High School',
      'stopType': '-1'
    }, {
      'id': 22,
      'stopName': '下湳',
      'stopNameEng': 'Xianan',
      'stopType': '-1'
    }, {
      'id': 23,
      'stopName': '中湳',
      'stopNameEng': 'Zhongnan',
      'stopType': '-1'
    }, {
      'id': 24,
      'stopName': '頂湳',
      'stopNameEng': 'Dingnan',
      'stopType': '-1'
    }, {
      'id': 25,
      'stopName': '虎尾科技大學',
      'stopNameEng': 'NFU',
      'stopType': '-1'
    }, {
      'id': 26,
      'stopName': '虎尾',
      'stopNameEng': 'Huwei',
      'stopType': '-1'
    }, {
      'id': 27,
      'stopName': '勝源',
      'stopNameEng': 'Shengyuan',
      'stopType': '-1'
    }, {
      'id': 28,
      'stopName': '埒內社區',
      'stopNameEng': 'Lenei Community',
      'stopType': '-1'
    }, {
      'id': 29,
      'stopName': '埒內',
      'stopNameEng': 'Lenei',
      'stopType': '-1'
    }, {
      'id': 30,
      'stopName': '汕尾',
      'stopNameEng': 'Shanwei',
      'stopType': '-1'
    }, {
      'id': 31,
      'stopName': '虎尾國中',
      'stopNameEng': 'Huwei Junior High',
      'stopType': '0'
    }, {
      'id': 32,
      'stopName': '半路店',
      'stopNameEng': 'Banludian',
      'stopType': '1'
    }, {
      'id': 33,
      'stopName': '中溪',
      'stopNameEng': 'Zhongxi',
      'stopType': '1'
    }, {
      'id': 34,
      'stopName': '東過溪',
      'stopNameEng': 'Dongguoxi',
      'stopType': '1'
    }, {
      'id': 35,
      'stopName': '崁腳',
      'stopNameEng': 'Kanjiao',
      'stopType': '1'
    }, {
      'id': 36,
      'stopName': '大路墘',
      'stopNameEng': 'Daluqian',
      'stopType': '1'
    }, {
      'id': 37,
      'stopName': '惠來國小',
      'stopNameEng': 'Huilai ES.',
      'stopType': '1'
    }, {
      'id': 38,
      'stopName': '惠來厝',
      'stopNameEng': 'Huilaicuo',
      'stopType': '1'
    }, {
      'id': 39,
      'stopName': '溪底仔',
      'stopNameEng': 'Xi Di Zi',
      'stopType': '1'
    }, {
      'id': 40,
      'stopName': '大美瓦斯廠',
      'stopNameEng': 'Damei Gas Factory',
      'stopType': '1'
    }, {
      'id': 41,
      'stopName': '大美',
      'stopNameEng': 'Damei',
      'stopType': '1'
    }, {
      'id': 42,
      'stopName': '榮橋新村',
      'stopNameEng': 'Rongqiao Village',
      'stopType': '1'
    }, {
      'id': 43,
      'stopName': '豐泰',
      'stopNameEng': 'Fengtai',
      'stopType': '1'
    }, {
      'id': 44,
      'stopName': '虎尾溪',
      'stopNameEng': 'Huweixi',
      'stopType': '1'
    }, {
      'id': 45,
      'stopName': '正心中學',
      'stopNameEng': 'Zhengxin High school',
      'stopType': '1'
    }, {
      'id': 46,
      'stopName': '電力公司',
      'stopNameEng': 'Taiwan Power Company',
      'stopType': '1'
    }, {
      'id': 47,
      'stopName': '斗六',
      'stopNameEng': 'Douliu',
      'stopType': '1'
    }, {
      'id': 48,
      'stopName': '白花墓',
      'stopNameEng': 'Bai hua mu',
      'stopType': '-1'
    }, {
      'id': 49,
      'stopName': '元長1',
      'stopNameEng': 'Yuanzhang1',
      'stopType': '-1'
    }, {
      'id': 50,
      'stopName': '元長',
      'stopNameEng': 'Yuanchang',
      'stopType': '-1'
    }, {
      'id': 51,
      'stopName': '子茂',
      'stopNameEng': 'Zimau',
      'stopType': '-1'
    }, {
      'id': 52,
      'stopName': '和平國小',
      'stopNameEng': 'Heping ES.',
      'stopType': '-1'
    }, {
      'id': 53,
      'stopName': '秀潭',
      'stopNameEng': 'Xiutan',
      'stopType': '-1'
    }, {
      'id': 54,
      'stopName': '奮起湖',
      'stopNameEng': 'Fenqihu',
      'stopType': '-1'
    }, {
      'id': 55,
      'stopName': '義雲宮',
      'stopNameEng': 'Yiyun Temple',
      'stopType': '-1'
    }, {
      'id': 56,
      'stopName': '新興',
      'stopNameEng': 'Xinxing',
      'stopType': '-1'
    }, {
      'id': 57,
      'stopName': '下店',
      'stopNameEng': 'Xiadian',
      'stopType': '-1'
    }, {
      'id': 58,
      'stopName': '土庫商工',
      'stopNameEng': 'Tuku Vocational High',
      'stopType': '-1'
    }, {
      'id': 59,
      'stopName': '土庫',
      'stopNameEng': 'Tuku',
      'stopType': '-1'
    }, {
      'id': 60,
      'stopName': '永年中學',
      'stopNameEng': 'Yongnian High School',
      'stopType': '-1'
    }, {
      'id': 61,
      'stopName': '下湳',
      'stopNameEng': 'Xianan',
      'stopType': '-1'
    }, {
      'id': 62,
      'stopName': '中湳',
      'stopNameEng': 'Zhongnan',
      'stopType': '-1'
    }, {
      'id': 63,
      'stopName': '頂湳',
      'stopNameEng': 'Dingnan',
      'stopType': '-1'
    }, {
      'id': 64,
      'stopName': '虎尾科技大學',
      'stopNameEng': 'NFU',
      'stopType': '-1'
    }, {
      'id': 65,
      'stopName': '虎尾',
      'stopNameEng': 'Huwei',
      'stopType': '-1'
    }, {
      'id': 66,
      'stopName': '勝源',
      'stopNameEng': 'Shengyuan',
      'stopType': '-1'
    }, {
      'id': 67,
      'stopName': '埒內社區',
      'stopNameEng': 'Lenei Community',
      'stopType': '-1'
    }, {
      'id': 68,
      'stopName': '埒內',
      'stopNameEng': 'Lenei',
      'stopType': '-1'
    }, {
      'id': 69,
      'stopName': '汕尾',
      'stopNameEng': 'Shanwei',
      'stopType': '-1'
    }, {
      'id': 70,
      'stopName': '虎尾國中',
      'stopNameEng': 'Huwei Junior High',
      'stopType': '1'
    }, {
      'id': 71,
      'stopName': '半路店',
      'stopNameEng': 'Banludian',
      'stopType': '1'
    }, {
      'id': 72,
      'stopName': '中溪',
      'stopNameEng': 'Zhongxi',
      'stopType': '1'
    }, {
      'id': 73,
      'stopName': '東過溪',
      'stopNameEng': 'Dongguoxi',
      'stopType': '1'
    }, {
      'id': 74,
      'stopName': '崁腳',
      'stopNameEng': 'Kanjiao',
      'stopType': '1'
    }, {
      'id': 75,
      'stopName': '大路墘',
      'stopNameEng': 'Daluqian',
      'stopType': '1'
    }, {
      'id': 76,
      'stopName': '惠來國小',
      'stopNameEng': 'Huilai ES.',
      'stopType': '1'
    }, {
      'id': 77,
      'stopName': '惠來厝',
      'stopNameEng': 'Huilaicuo',
      'stopType': '1'
    }, {
      'id': 78,
      'stopName': '溪底仔',
      'stopNameEng': 'Xi Di Zi',
      'stopType': '1'
    }, {
      'id': 79,
      'stopName': '大美瓦斯廠',
      'stopNameEng': 'Damei Gas Factory',
      'stopType': '1'
    }, {
      'id': 80,
      'stopName': '大美',
      'stopNameEng': 'Damei',
      'stopType': '1'
    }, {
      'id': 81,
      'stopName': '榮橋新村',
      'stopNameEng': 'Rongqiao Village',
      'stopType': '1'
    }
  ],
}

export const mockFromToData = {
  ChiaYi: {
    fromTo1: '嘉義',
    fromTo2: '第一銀行',
    className: 'fromTo',
    fontSize: '24',
    y: 100,
  },
  Yunlin: {
    className: 'fromTo-Yunlin-story',
    x: 100,
    y: 100,
    fontSize: 24,
    fromTo: ['北港', '斗六'],
    fromToEng: ['Xigang', 'Erlin Station'],
    pass: ['經惠來厝', '虎尾、土庫、奮起湖、元長'],
    passFontSize: 10,
  },
  ChanHua: {
    className: 'fromTo-Yunlin-story',
    fromTo1: '西港',
    fromToEng1: 'Xigang',
    fromTo2Text: '二林(頂莊、臺西村)',
    fromToEng2: 'Erlin Station',
    // y: 100,
    fromTo1W: 100,
    fromTo2W: 300,
    fontSize: 24,
  }
}